version: "3.9"

services:
  app:
    build: .
    container_name: ai-assistant-app
    environment:
      TZ: ${TZ}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_WEBHOOK_SECRET: ${TG_WEBHOOK_SECRET}
      OPENAI_TOKEN: ${OPENAI_TOKEN}
      PROXY_HOST: ${PROXY_HOST}
      PROXY_PORT: ${PROXY_PORT}
      PROXY_USER: ${PROXY_USER}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      R2DBC_URL: ${R2DBC_URL}
      JDBC_URL: ${JDBC_URL}
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - app-net

  nginx:
    image: nginx:1.27-alpine
    container_name: ai-assistant-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/certs:/etc/nginx/certs:ro
